#ifndef GFXTK_COMBINEDTEXTURESAMPLERBINDINGTYPE_HPP
#define GFXTK_COMBINEDTEXTURESAMPLERBINDINGTYPE_HPP

#include "microsoft_fix.hpp"

namespace gfxtk {
    struct GFXTK_EXPORT CombinedTextureSamplerBindingLayout {};
}

#endif //GFXTK_COMBINEDTEXTURESAMPLERBINDINGTYPE_HPP
