#ifndef GFXTK_VERTEXFORMAT_HPP
#define GFXTK_VERTEXFORMAT_HPP

namespace gfxtk {
    enum class VertexFormat {
        Invalid = 0,
        Uchar,
        Uchar2,
        Uchar3,
        Uchar4,
        Char,
        Char2,
        Char3,
        Char4,
        UcharNorm,
        Uchar2Norm,
        Uchar3Norm,
        Uchar4Norm,
        CharNorm,
        Char2Norm,
        Char3Norm,
        Char4Norm,
        Ushort,
        Ushort2,
        Ushort3,
        Ushort4,
        Short,
        Short2,
        Short3,
        Short4,
        UshortNorm,
        Ushort2Norm,
        Ushort3Norm,
        Ushort4Norm,
        ShortNorm,
        Short2Norm,
        Short3Norm,
        Short4Norm,
        Half,
        Half2,
        Half3,
        Half4,
        Float,
        Float2,
        Float3,
        Float4,
        Uint,
        Uint2,
        Uint3,
        Uint4,
        Int,
        Int2,
        Int3,
        Int4,
    };
}

#endif //GFXTK_VERTEXFORMAT_HPP
